### ISSUE TITLE
Client/tester feedback

### ISSUE THREAD

**Issue by lizzie-madebyon** [on-associates/rekreate-webflow-scripts#22]
- [ ] Homepage - hero image - suggesting to scroll down the hero image at the same time as resizing as with no prompt to scroll people don't quite know to do that. Currently it first rounds the corners BEFORE resizing the image. Suggest that the rounding of the corners happens SIMULTANEOUSLY to the resizing of the image. Initial scroll (as a first time user) doesn't show perceptible movement. 
- [ ] Property page - navigating back to the property section on the homepage - When you click on one of the office opportunities from HERE (attached image), my natural reaction would be that I can then close that opportunity to go back to HERE so that I can click on a different one. However, when you do click on an opportunity (see image), you can't go back there. You have to know to click on the logo to go back to home (and then scroll down to the opportunities again), or scroll right to the bottom to see a small selection of other properties. It should be easier to go back - like a X on top right to close that opportunity and return to the options that you were previously at.

![Image](https://github.com/on-associates/rekreate-webflow-scripts/assets/89518778/4fa4d937-0fc9-474c-ac5e-169b5faf9f9f)

![Image](https://github.com/on-associates/rekreate-webflow-scripts/assets/89518778/d7275c05-bf1d-4643-b32b-2bbb4659258f)

**Comment by Werther-V** [comment]
agree with the animation of rounding corners and resizing to happen at the same time to make it snappier. i’d hope that’s a relatively easy thing for milan to implement?
i don’t think adding a close icon is obvious enough – it would evoke the idea of a pop up which these property pages really are not. we could however add a ‘see more properties’ button in the top right (where we usually have ‘get in touch’). it does make the module a bit lower down on the page a bit obsolete (which was the main way for people to get back to the other properties). but i don’t think that’s a big issue
