### ISSUE TITLE
Meta descriptions

### ISSUE THREAD

**Issue by lizzie-madebyon** [on-associates/rekreate-webflow-scripts#23]
Adding meta descriptions into Webflow: https://docs.google.com/spreadsheets/d/1TQrEr-BhOIqmlUuTpowqJkxLE5q7ihoqhZOgGHToF20/edit#gid=0

**Comment by lizzie-madebyon** [comment]
@MilanVetnic as this is a short task let's pick this up

**Comment by MilanVetnic** [comment]
Completed
