### ISSUE TITLE
Adding social links

### ISSUE THREAD

**Issue by lizzie-madebyon** [on-associates/rekreate-webflow-scripts#25]
LinkedIn: https://www.linkedin.com/company/rekreate-ltd/
Twitter: https://twitter.com/ReKreate_
Instagram: https://www.instagram.com/rekltd/
Pinterest: https://www.pinterest.co.uk/REKLTD/

**Comment by lizzie-madebyon** [comment]
Hey @kaonkd please can you find an icon for Pinterest for Milan to add to the project? Thanks

**Comment by MilanVetnic** [comment]
Added and updated

**Comment by kaonkd** [comment]
Thanks for updating this! -  @MilanVetnic
