### ISSUE TITLE
Website re-direct

### ISSUE THREAD

**Issue by claudia-miquel** [on-associates/rekreate-webflow-scripts#29]
Hey @MilanVetnic ! 

It should be the case that rekreate.co redirects to rekreate.com – it doesn't currently. Would you be able to have a look and see if you can implement? I checked on Webflow but obviously you can only do "/" redirects from there. Not sure where their domain is parked to do a DNS level redirect. Let me know if client needs spoken to in order to resolve. 

No high priority on this one so let me know when you have the capacity to look.

Thanks,
Claudia

**Comment by MilanVetnic** [comment]
Hey @claudia-miquel 

We've sent them this message last week, but no update was made from the client:


Lizzie:
Also one last thing, it would be great if you can redirect [rekreate.co](http://rekreate.co/) to [rekreate.com](http://rekreate.com/) in 123 reg just so anyone who clicks on a [rekreate.co](http://rekreate.co/) link doesn’t lead to a dead end. Milan can update this in 123 reg if needed - we would just need the login details (which can be sent to me via the Bitwarden password share like last time)

**Comment by claudia-miquel** [comment]
@MilanVetnic Ah thanks Milan! Good to know.
