### ISSUE TITLE
Property - layout issues with the regular overlay haven’t been addressed (see liam’s comments in figma)

### ISSUE THREAD

**Issue by ONLiam** [on-associates/rekreate-webflow-scripts#3]

**Comment by ONLiam** [comment]
@lizzie-madebyon could you clarify what part of the page this ticket refers to please?

**Comment by lizzie-madebyon** [comment]
@ONLiam I'm not 100% sure but it might be related to one of the [comments](https://www.figma.com/file/8npd2Q6q4zzNn6vWmOOf6l?node-id=1653:34440#439720166) that were left on the overlay?

**Comment by ONLiam** [comment]
This is not resolved @kaonkd / @MilanVetnic — the design is showing that the content is inset by a column on each side

(see screenshot below. Top image is the design, bottom is the build)
<img width="853" alt="Screenshot 2023-05-26 at 15 46 41" src="https://github.com/on-associates/rekreate-webflow-scripts/assets/102548490/7026c6c4-cf58-4c78-b12f-6dd39226e991">

**Comment by lizzie-madebyon** [comment]
Hey @MilanVetnic is this one completed?
