### ISSUE TITLE
(mobile) Double check all button sizes – eg. get in touch bottom module and button in footer should be the same size (mobile & desktop)

### ISSUE THREAD

**Issue by lizzie-madebyon** [on-associates/rekreate-webflow-scripts#8]

**Comment by MilanVetnic** [comment]
This has been updated

**Comment by lizzie-madebyon** [comment]
These two buttons are different sizes for me 

![Image](https://github.com/on-associates/rekreate-webflow-scripts/assets/89518778/925b2669-3d8a-4f58-a03f-6d656889fea4)

**Comment by MilanVetnic** [comment]
Updated
